#!/usr/bin/env python3
"""Regenerate the SynthDef collection tree in README.md from synthdefs/.

    python3 tools/update_synthdef_tree.py

Generic synths are listed by the name their ~synthCreator call gives them,
with the description from the same call; Defaults and old-format sources are
listed by file. Only the block between the synthdef-tree markers is rewritten.
"""
import os
import re
import sys

ADDON = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.join(ADDON, "synthdefs")
README = os.path.join(ADDON, "README.md")
START = "<!-- synthdef-tree:start -->"
END = "<!-- synthdef-tree:end -->"

CREATOR = re.compile(r'~synthCreator\s*\.\s*(?:value\s*)?\(\s*"([^"]+)"')
DESCRIPTION = re.compile(r'description\s*:\s*"([^"]*)"')


def synths_in(path):
    """[(name, description)] for every ~synthCreator call in a source."""
    with open(path, errors="replace") as f:
        text = f.read()
    calls = list(CREATOR.finditer(text))
    found = []
    for i, call in enumerate(calls):
        end = calls[i + 1].start() if i + 1 < len(calls) else len(text)
        description = DESCRIPTION.search(text, call.end(), end)
        found.append((call.group(1), description.group(1).strip() if description else ""))
    return found


def entries(folder):
    """Lines describing the sources directly inside folder."""
    lines = []
    for name in sorted(os.listdir(folder), key=str.lower):
        path = os.path.join(folder, name)
        if not os.path.isfile(path) or not name.endswith((".scd", ".sc")):
            continue
        synths = synths_in(path) if name.endswith(".scd") else []
        if synths:
            lines += [s + (" — " + d if d else "") for s, d in synths]
        else:
            lines.append(name)
    return sorted(lines, key=str.lower)


def tree(folder, prefix=""):
    """Box-drawing tree of folder: subfolders first, then their contents."""
    subfolders = sorted(
        (d for d in os.listdir(folder)
         if os.path.isdir(os.path.join(folder, d)) and d != "CompiledSynthdefs" and not d.startswith(".")),
        key=str.lower)
    items = [(d + "/", os.path.join(folder, d)) for d in subfolders]
    items += [(line, None) for line in entries(folder)]
    out = []
    for i, (label, path) in enumerate(items):
        last = i == len(items) - 1
        out.append(prefix + ("└── " if last else "├── ") + label)
        if path:
            out += tree(path, prefix + ("    " if last else "│   "))
    return out


def count(folder):
    total = 0
    for dirpath, dirnames, filenames in os.walk(folder):
        for f in filenames:
            if f.endswith(".scd"):
                total += len(synths_in(os.path.join(dirpath, f))) or 1
    return total


def section():
    categories = sorted(
        (d for d in os.listdir(ROOT) if os.path.isdir(os.path.join(ROOT, d)) and d not in ("Oceanode",)),
        key=lambda d: (d in ("Defaults", "Compatibility"), d.lower()))
    generic = sum(count(os.path.join(ROOT, c)) for c in categories if c not in ("Defaults", "Compatibility"))
    out = [
        START,
        "<!-- Generated by tools/update_synthdef_tree.py: edit the sources, not this list. -->",
        "",
        "The SuperCollider sources live in [`synthdefs/`](synthdefs/) ({} generic synths). "
        "Generic synths are built for any channel count with `~synthCreator`; "
        "`Defaults/` holds the synths of the server and of nodes with a C++ counterpart; "
        "`Compatibility/` keeps older definitions. See [`synthdefs/README.md`](synthdefs/README.md).".format(generic),
        "",
    ]
    for category in categories:
        folder = os.path.join(ROOT, category)
        out += [
            "<details>",
            "<summary><b>{}</b> ({})</summary>".format(category, count(folder)),
            "",
            "```",
            category + "/",
        ]
        out += tree(folder)
        out += ["```", "", "</details>", ""]
    out.append(END)
    return "\n".join(out)


def main():
    with open(README) as f:
        readme = f.read()
    block = section()
    if START in readme and END in readme:
        before = readme[:readme.index(START)]
        after = readme[readme.index(END) + len(END):]
        readme = before + block + after
    else:
        readme = readme.rstrip("\n") + "\n\n## SynthDef collection\n\n" + block + "\n"
    with open(README, "w") as f:
        f.write(readme)
    print("README.md: SynthDef tree updated")


if __name__ == "__main__":
    sys.exit(main())
