//
//  scDynGenNode.cpp
//  ofxOceanodeSuperCollider
//
//  Live-coding EEL2 DSP node powered by DynGen.
//
//  Features implemented:
//    1. Per-channel vector params: p<i> is an n-element array NamedControl.
//       EEL2: in(n + pi*n + ci). Mono unchanged: in(1 + pi).
//    2. Param renaming: //@param Name annotations rename sliders live.
//    3. Dynamic param count: only registered as many sliders as annotations.
//    4. Open/Save + script dropdown (data/Supercollider/dyngenScripts/).
//    5. Word-wrap view: toggle button in editor toolbar.
//    6. AI code generation: "AI" toolbar button → Claude writes EEL2 via API.
//       Set ANTHROPIC_API_KEY env var or write key to ~/.claude/api_key.
//

#include "scDynGenNode.h"
#include "ofxSCSynth.h"
#include "ofxSCServer.h"
#include "ofxSuperCollider.h"
#include "imgui.h"
#include "ofJson.h"

#include <algorithm>
#include <sstream>
#include <fstream>
#include <cstring>
#include <cmath>
#include <climits>
#include <chrono>
#include <cstdio>   // popen / pclose / fgets

// ─────────────────────────────────────────────────────────────────────────────
// Static member definitions
// ─────────────────────────────────────────────────────────────────────────────

std::bitset<scDynGenNode::kMaxSlots> scDynGenNode::sSlotPool;
std::mutex                           scDynGenNode::sSlotMutex;

// Slot hashes — generated by dyngen.scd via DynGenDef.prHashSymbol(\dyngenSlotN).
const int scDynGenNode::kSlotHashes[scDynGenNode::kMaxSlots] = {
    -93156,  // slot  0 = \dyngenSlot0
     595923, // slot  1 = \dyngenSlot1
     439118, // slot  2 = \dyngenSlot2
     810776, // slot  3 = \dyngenSlot3
     195493, // slot  4 = \dyngenSlot4
     249700, // slot  5 = \dyngenSlot5
     420841, // slot  6 = \dyngenSlot6
       5245, // slot  7 = \dyngenSlot7
     635120, // slot  8 = \dyngenSlot8
    -511249, // slot  9 = \dyngenSlot9
    -226989, // slot 10 = \dyngenSlot10
    -692348, // slot 11 = \dyngenSlot11
    -573336, // slot 12 = \dyngenSlot12
     809716, // slot 13 = \dyngenSlot13
     212865, // slot 14 = \dyngenSlot14
     105950, // slot 15 = \dyngenSlot15
};

// ─────────────────────────────────────────────────────────────────────────────
// Hash computation
// ─────────────────────────────────────────────────────────────────────────────

int32_t scDynGenNode::scStringHash(const char* s) {
    uint32_t hash = 0;
    while(*s) {
        hash = hash * 1664525u + 1013904223u + (unsigned char)*s++;
    }
    return (int32_t)hash;
}

int scDynGenNode::computeSlotHash(int slotIdx) {
    if(slotIdx >= 0 && slotIdx < kMaxSlots && kSlotHashes[slotIdx] != 0)
        return kSlotHashes[slotIdx];

    std::string name = "dyngenSlot" + std::to_string(slotIdx);
    int32_t h    = scStringHash(name.c_str());
    int64_t absH = (h < 0) ? -(int64_t)h : (int64_t)h;
    int64_t modH = absH % (int64_t)(1 << 20);
    int     sign = (h > 0) ? 1 : (h < 0) ? -1 : 0;
    return (int)(modH * sign);
}

// ─────────────────────────────────────────────────────────────────────────────
// Slot pool
// ─────────────────────────────────────────────────────────────────────────────

int scDynGenNode::acquireSlot() {
    std::lock_guard<std::mutex> lk(sSlotMutex);
    for(int i = 0; i < kMaxSlots; i++) {
        if(!sSlotPool.test(i)) {
            sSlotPool.set(i);
            return i;
        }
    }
    ofLogError("scDynGenNode") << "Slot pool exhausted — increase kMaxSlots.";
    return -1;
}

void scDynGenNode::releaseSlot(int idx) {
    if(idx < 0 || idx >= kMaxSlots) return;
    std::lock_guard<std::mutex> lk(sSlotMutex);
    sSlotPool.reset(idx);
}

// ─────────────────────────────────────────────────────────────────────────────
// Constructor / Destructor
// ─────────────────────────────────────────────────────────────────────────────

scDynGenNode::scDynGenNode() : scNode("DynGen") {
    std::memset(editorBuf, 0, sizeof(editorBuf));
    std::memset(llmPromptBuf, 0, sizeof(llmPromptBuf));
    eel2StatusMsg = "Ready";

    // ── Feature 6: load Anthropic API key ────────────────────────────────────
    // Priority:
    //   1. ANTHROPIC_API_KEY environment variable
    //   2. <data>/anthropic_api_key.txt   (easiest — just drop the file in data/)
    //   3. ~/.anthropic_api_key
    auto tryReadKey = [&](const std::string& path) {
        std::ifstream f(path);
        if(f) { std::getline(f, llmApiKey); return !llmApiKey.empty(); }
        return false;
    };
    const char* envKey = std::getenv("ANTHROPIC_API_KEY");
    if(envKey && *envKey) {
        llmApiKey = std::string(envKey);
    } else if(!tryReadKey(ofToDataPath("anthropic_api_key.txt"))) {
        tryReadKey(ofFilePath::getUserHomeDir() + "/.anthropic_api_key");
    }
    // Trim any trailing whitespace / newlines from the key
    while(!llmApiKey.empty() && (llmApiKey.back() == '\n' ||
                                  llmApiKey.back() == '\r' ||
                                  llmApiKey.back() == ' '))
        llmApiKey.pop_back();
}

scDynGenNode::~scDynGenNode() {
    try {
        listeners.unsubscribeAll();
        paramListeners.clear();

        if(slotIndex >= 0) {
            int hash = getSlotHash();
            for(auto& pair : synthInstances) {
                if(pair.second) {
                    ofxOscMessage freeMsg;
                    freeMsg.setAddress("/cmd");
                    freeMsg.addStringArg("dyngenfree");
                    freeMsg.addIntArg(hash);
                    pair.first->sendMsg(freeMsg);

                    pair.second->free();
                    delete pair.second;
                }
            }
            synthInstances.clear();
            releaseSlot(slotIndex);
        }
    } catch(const std::exception& e) {
        ofLogError("scDynGenNode") << "Destructor: " << e.what();
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// setup()
// ─────────────────────────────────────────────────────────────────────────────

void scDynGenNode::setup() {

    // ── Core parameter ────────────────────────────────────────────────────────
    addParameter(numChannels.set("Num Channels", 1, 1, kMaxChans));

    // NOTE: Param slots p0..p7 are NOT registered here (Feature 3).
    // They are added dynamically by updateParamCount() when @param annotations
    // are parsed from the EEL2 code.  activeParamCount starts at 0.

    // ── EEL2 code (persisted as inspector parameter) ──────────────────────────
    const std::string defaultCode =
        "// DynGen EEL2 - live DSP scripting\n"
        "// Audio inputs:  in(0) .. in(n-1)        where n = Num Channels\n"
        "// Param access:  in(n + pi*n + ci)        param pi, channel ci\n"
        "//   Mono shortcut: in(1)=p0, in(2)=p1 ...\n"
        "// Outputs: out0, out1, ..., out(n-1)\n"
        "// Declare params: //@param Name : default, min, max\n"
        "\n"
        "@sample\n"
        "out0 = in(0);\n";

    addInspectorParameter(eel2CodeParam.set("EEL2 Code", defaultCode));
    std::strncpy(editorBuf, defaultCode.c_str(), kBufSize - 1);

    // ── Inspector: editor dimensions ──────────────────────────────────────────
    addInspectorParameter(editorWidth.set("Editor Width",  380.0f, 160.0f, 800.0f));
    addInspectorParameter(editorHeight.set("Editor Height", 220.0f,  80.0f, 600.0f));

    // ── Audio ports ───────────────────────────────────────────────────────────
    scNode::addInput("In");
    scNode::addOutput("Out");

    // ── Listeners ─────────────────────────────────────────────────────────────

    // numChannels → replace synths (same slot, same code)
    listeners.push(numChannels.newListener([this](int& ch) {
        if(ch < 1 || ch > kMaxChans) return;
        if(oldNumChannels != ch) {
            for(auto& pair : synthInstances) {
                if(!pair.second) continue;
                // Canonical kAddAction_replace: swap pointer first so
                // resendParams queues params on new synth as init-args.
                int oldID       = pair.second->nodeID;
                ofxSCSynth* old = pair.second;
                ofxSCSynth* newSynth = new ofxSCSynth(getSynthDefName(), pair.first);
                pair.second = newSynth;
                resendParams.notify();
                newSynth->createAndRun(4, oldID, getActive());
                delete old;
            }
        }
        oldNumChannels = ch;
    }));

    // eel2CodeParam changed (preset load, file open, update() debounce, or AI)
    listeners.push(eel2CodeParam.newListener([this](std::string& code) {
        std::strncpy(editorBuf, code.c_str(), kBufSize - 1);
        editorBuf[kBufSize - 1] = '\0';
        // Parse annotations → update param count + names (Features 2+3)
        auto anns = parseAnnotations(code);
        mergeParamNames(anns);
        updateParamCount((int)anns.size(), anns);
        // Recreate synths when flagged (AI generation or file load) so @init
        // executes fresh with the new script.  Skipped for live-typing edits.
        if(codeRequiresRecreate) {
            codeRequiresRecreate = false;
            for(auto& pair : synthInstances) {
                if(!pair.second) continue;
                // Mirror createSynth: send code WITHOUT BLatency so SC processes
                // /cmd dyngenscript before /s_new (which fires ~200ms later).
                // Sending both with BLatency races at the same SC timestamp.
                bool wasLatency = pair.first->getBLatency();
                pair.first->setBLatency(false);
                sendCodeToServer(pair.first);
                pair.first->setBLatency(wasLatency);
                // Canonical kAddAction_replace ordering: swap pointer first so
                // resendParams queues params on the new synth object, then
                // createAndRun sends them as init-args in /s_new.
                int oldID        = pair.second->nodeID;
                ofxSCSynth* old  = pair.second;
                ofxSCSynth* newSynth = new ofxSCSynth(getSynthDefName(), pair.first);
                pair.second = newSynth;
                resendParams.notify();
                newSynth->createAndRun(4, oldID, getActive());
                delete old;
            }
        } else {
            // Live-typing edit: just push new code, no synth recreation needed
            sendCodeToAllServers();
        }
        eel2StatusMsg = "Loaded";
    }));

    // resendParams: push all NamedControls to every live synth
    listeners.push(resendParams.newListener([this]() {
        for(auto& pair : synthInstances) {
            if(pair.second) sendParamsToSynth(pair.first);
        }
    }));

    // ── ImGui editor widget ───────────────────────────────────────────────────
    // Store in a member so updateParamCount() can remove+re-add it to keep
    // the params ordered BEFORE the editor in the Oceanode panel.
    // We initialize with set(name, func) so the name is established, then
    // register directly with addParameter using the custom-region flags.
    std::function<void()> drawFn = [this](){ drawEditor(); };
    editorRegion.set("EEL2 Editor", drawFn);
    addParameter(editorRegion,
        ofxOceanodeParameterFlags_DisableInConnection  |
        ofxOceanodeParameterFlags_DisableOutConnection |
        ofxOceanodeParameterFlags_DisableSavePreset    |
        ofxOceanodeParameterFlags_DisableSaveProject);

    // Ensure scripts directory exists
    ofDirectory::createDirectory(ofToDataPath("Supercollider/dyngenScripts"), false, true);
}

// ─────────────────────────────────────────────────────────────────────────────
// update()
// ─────────────────────────────────────────────────────────────────────────────

void scDynGenNode::update(ofEventArgs&) {

    // ── Feature 4: deferred file dialogs ─────────────────────────────────────
    // Dialogs are triggered from drawEditor() but executed here (outside ImGui)
    if(pendingLoadDialog) {
        pendingLoadDialog = false;
        ofFileDialogResult r = ofSystemLoadDialog(
            "Load EEL2 Script", false,
            ofToDataPath("Supercollider/dyngenScripts"));
        if(r.bSuccess) loadScriptFile(r.filePath);
    }
    if(pendingSaveDialog) {
        pendingSaveDialog = false;
        ofFileDialogResult r = ofSystemSaveDialog(
            "dyngen_script.eel2", "Save EEL2 Script");
        if(r.bSuccess) saveScriptFile(r.filePath);
    }

    // ── Feature 6: poll LLM future ────────────────────────────────────────────
    if(llmPending.load() && llmFuture.valid()) {
        if(llmFuture.wait_for(std::chrono::seconds(0)) == std::future_status::ready) {
            std::string result = llmFuture.get();
            bool isError = (result.rfind("// Error:", 0) == 0 ||
                            result.rfind("// API error", 0) == 0);
            if(isError) {
                llmStatusMsg = result;
                llmHasError  = true;
            } else {
                std::strncpy(editorBuf, result.c_str(), kBufSize - 1);
                editorBuf[kBufSize - 1] = '\0';
                codeDirty            = true;
                codeDirtyTimer       = 0.0f;
                codeRequiresRecreate = true;   // force @init on new script
                eel2StatusMsg        = "AI generated";
                llmHasError          = false;
            }
            llmPending.store(false);
            llmDone.store(true);
        }
    }

    // ── Debounce code changes ─────────────────────────────────────────────────
    if(!codeDirty) return;

    codeDirtyTimer += ofGetLastFrameTime();
    if(codeDirtyTimer < kDebounce) return;

    codeDirty      = false;
    codeDirtyTimer = 0.0f;

    std::string newCode(editorBuf);
    eel2CodeParam.set(newCode);  // fires listener → annotations + send

    eel2StatusMsg = "Code sent";
}

// ─────────────────────────────────────────────────────────────────────────────
// activate / deactivate
// ─────────────────────────────────────────────────────────────────────────────

void scDynGenNode::activate() {
    for(auto& pair : synthInstances)
        if(pair.second) pair.second->run(true);
}

void scDynGenNode::deactivate() {
    for(auto& pair : synthInstances)
        if(pair.second) pair.second->run(false);
}

// ─────────────────────────────────────────────────────────────────────────────
// scNode interface
// ─────────────────────────────────────────────────────────────────────────────

void scDynGenNode::buildSynth(ofxSCServer* server) {
    if(!server) return;

    if(slotIndex < 0) {
        slotIndex = acquireSlot();
        if(slotIndex < 0) { eel2StatusMsg = "Error: no free slots"; return; }
        ofLogNotice("scDynGenNode") << "Acquired slot " << slotIndex
                                    << " (hash=" << getSlotHash() << ")";
    }
    synthInstances[server] = new ofxSCSynth(getSynthDefName(), server);
}

void scDynGenNode::createSynth(ofxSCServer* server) {
    if(!server || !synthInstances.count(server) || !synthInstances[server]) return;
    if(slotIndex < 0) return;

    try {
        // Send dyngenscript WITHOUT BLatency so SC registers it immediately.
        // /s_new fires ~200ms later (with BLatency), by which time the script
        // is already in the slot.
        bool wasLatency = server->getBLatency();
        server->setBLatency(false);
        sendCodeToServer(server);
        server->setBLatency(wasLatency);

        resendParams.notify();
        synthInstances[server]->createAndRun(0, 1, getActive());
        activeServerCount++;
        eel2StatusMsg = "Script sent";

    } catch(const std::exception& e) {
        ofLogError("scDynGenNode") << "createSynth: " << e.what();
        eel2StatusMsg = std::string("Error: ") + e.what();
    }
}

void scDynGenNode::free(ofxSCServer* server) {
    if(!server) return;
    try {
        if(synthInstances.count(server) && synthInstances[server]) {
            synthInstances[server]->free();
            delete synthInstances[server];
            synthInstances.erase(server);
            activeServerCount = std::max(0, activeServerCount - 1);
        }
        inputBuses.erase(server);
        outputBuses.erase(server);
        // NOTE: do NOT send /cmd dyngenfree here — this is called during graph
        // recomputes where the node is immediately recreated.  dyngenfree is
        // sent only in the destructor (true node destruction).
    } catch(const std::exception& e) {
        ofLogError("scDynGenNode") << "free: " << e.what();
    }
}

void scDynGenNode::setInputBus(ofxSCServer* server, scNode* node, int bus) {
    if(!server || !node) return;
    inputBuses[server][node] = bus;
    if(synthInstances.count(server) && synthInstances[server])
        synthInstances[server]->set("in", bus);
}

void scDynGenNode::resetInputBusses(ofxSCServer* server, int targetBus) {
    if(!server) return;
    inputBuses[server].clear();
    if(synthInstances.count(server) && synthInstances[server])
        synthInstances[server]->set("in", targetBus);
}

void scDynGenNode::setOutputBus(ofxSCServer* server, int index, int bus) {
    if(!server) return;
    outputBuses[server][index] = bus;
    if(synthInstances.count(server) && synthInstances[server])
        synthInstances[server]->set("out", bus);
}

int scDynGenNode::getOutputBusIndex(ofxSCServer* server, int index) {
    if(outputBuses.count(server) && outputBuses[server].count(index))
        return outputBuses[server].at(index);
    return -1;
}

void scDynGenNode::moveSynthBefore(ofxSCServer* server, int nodeID) {
    if(!server || !synthInstances.count(server) || !synthInstances[server]) return;
    try {
        resendParams.notify();
        synthInstances[server]->moveBefore(nodeID);
    } catch(const std::exception& e) {
        ofLogError("scDynGenNode") << "moveSynthBefore: " << e.what();
    }
}

int scDynGenNode::getLastSynthID(ofxSCServer* server) {
    auto it = synthInstances.find(server);
    if(it != synthInstances.end() && it->second)
        return it->second->nodeID;
    return -1;
}

// ─────────────────────────────────────────────────────────────────────────────
// Preset handling
// ─────────────────────────────────────────────────────────────────────────────

void scDynGenNode::presetSave(ofJson& json) {
    // Save param values with stable index-based keys so they survive renames.
    // (Normal Oceanode serialization also saves them by their current name,
    // but stable keys make loading robust even after annotation changes.)
    for(int i = 0; i < activeParamCount; i++) {
        const auto& v = paramSlots[i].param.get();
        json["dyngen_p" + std::to_string(i)] = v;
    }
    json["dyngen_param_count"] = activeParamCount;
}

void scDynGenNode::presetRecallAfterSettingParameters(ofJson& json) {
    // Restore param values from stable index-based keys.
    // This runs after loadBeforeConnections has already set up the right
    // number of params and after Oceanode has set values from named keys,
    // so this is a belt-and-suspenders restore for renamed params.
    for(int i = 0; i < activeParamCount; i++) {
        std::string key = "dyngen_p" + std::to_string(i);
        if(json.contains(key) && json[key].is_array()) {
            std::vector<float> v;
            for(auto& e : json[key]) {
                if(e.is_number()) v.push_back(e.get<float>());
            }
            if(!v.empty()) paramSlots[i].param.set(v);
        }
    }
}

void scDynGenNode::loadBeforeConnections(ofJson& json) {
    // Deserialize the EEL2 code BEFORE connections are restored so the correct
    // number of param sliders exist when Oceanode tries to reconnect them.
    deserializeParameter(json, eel2CodeParam);
    const std::string code = eel2CodeParam.get();
    std::strncpy(editorBuf, code.c_str(), kBufSize - 1);
    editorBuf[kBufSize - 1] = '\0';
    auto anns = parseAnnotations(code);
    mergeParamNames(anns);
    updateParamCount((int)anns.size(), anns);
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

std::string scDynGenNode::getSynthDefName() const {
    int slot = (slotIndex >= 0) ? slotIndex : 0;
    return "DynGenWrapper_" + std::to_string(numChannels.get())
         + "_" + std::to_string(slot);
}

int scDynGenNode::getSlotHash() const {
    return computeSlotHash(slotIndex);
}

// Feature 1: expand a vector to exactly n values, broadcasting the last element.
std::vector<float> scDynGenNode::expandToChannels(const std::vector<float>& v, int n) const {
    std::vector<float> result(n);
    for(int i = 0; i < n; i++) {
        result[i] = v.empty() ? 0.0f : v[std::min((int)v.size() - 1, i)];
    }
    return result;
}

void scDynGenNode::sendParamsToSynth(ofxSCServer* server) {
    auto it = synthInstances.find(server);
    if(it == synthInstances.end() || !it->second) return;
    ofxSCSynth* synth = it->second;

    // Restore bus assignments
    if(inputBuses.count(server) && !inputBuses[server].empty())
        synth->set("in", inputBuses[server].begin()->second);
    if(outputBuses.count(server) && outputBuses[server].count(0))
        synth->set("out", outputBuses[server].at(0));

    int n = numChannels.get();

    // Feature 1: send all active params as n-element vectors (per-channel).
    // Inactive params are zeroed so any lingering values are silenced.
    for(int i = 0; i < kMaxParams; i++) {
        if(i < activeParamCount) {
            auto expanded = expandToChannels(paramSlots[i].param.get(), n);
            synth->set("p" + std::to_string(i), expanded);
        } else {
            // Zero out inactive param (scalar 0 works for both scalar and array NC)
            synth->set("p" + std::to_string(i), 0.0);
        }
    }
}

void scDynGenNode::sendCodeToServer(ofxSCServer* server) {
    if(!server || slotIndex < 0) return;

    const std::string code(editorBuf);
    int  hash      = getSlotHash();
    int  numParams = (int)accParamNames.size();

    size_t estimatedSize = 32 + code.size() + 4;
    for(auto& p : accParamNames) estimatedSize += p.size() + 8;

    static constexpr size_t kOscThreshold = 16000;

    if(estimatedSize < kOscThreshold) {
        ofxOscMessage msg;
        msg.setAddress("/cmd");
        msg.addStringArg("dyngenscript");
        msg.addIntArg(hash);
        msg.addStringArg(code);
        msg.addIntArg(numParams);
        for(auto& p : accParamNames) msg.addStringArg("_" + p);
        server->sendMsg(msg);
    } else {
        std::string tmpPath = ofGetTimestampString(
            ofGetEnv("TMPDIR", "/tmp") + "/dyngen_%Y%m%d_%H%M%S_%i.eel2");
        std::ofstream f(tmpPath);
        if(!f.is_open()) {
            ofLogError("scDynGenNode") << "Cannot write temp file: " << tmpPath;
            eel2StatusMsg = "Error: temp file write failed";
            return;
        }
        f << code;
        f.close();

        ofxOscMessage msg;
        msg.setAddress("/cmd");
        msg.addStringArg("dyngenfile");
        msg.addIntArg(hash);
        msg.addStringArg(tmpPath);
        msg.addIntArg(numParams);
        for(auto& p : accParamNames) msg.addStringArg("_" + p);
        server->sendMsg(msg);
    }
}

void scDynGenNode::sendCodeToAllServers() {
    for(auto& pair : synthInstances) {
        if(pair.second) sendCodeToServer(pair.first);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Param annotation parsing (Features 2+3)
// ─────────────────────────────────────────────────────────────────────────────

std::string scDynGenNode::trimStr(const std::string& s) {
    size_t a = s.find_first_not_of(" \t\r\n");
    if(a == std::string::npos) return "";
    size_t b = s.find_last_not_of(" \t\r\n");
    return s.substr(a, b - a + 1);
}

std::vector<scDynGenNode::ParamAnnotation>
scDynGenNode::parseAnnotations(const std::string& code) {
    std::vector<ParamAnnotation> result;
    std::istringstream ss(code);
    std::string line;

    while(std::getline(ss, line) && (int)result.size() < kMaxParams) {
        auto pos = line.find("//@param ");
        if(pos == std::string::npos) continue;

        std::string rest = line.substr(pos + 9);
        auto colon = rest.find(':');

        ParamAnnotation ann;
        if(colon == std::string::npos) {
            ann.name = trimStr(rest);
        } else {
            ann.name = trimStr(rest.substr(0, colon));
            std::string vals = rest.substr(colon + 1);
            std::istringstream vs(vals);
            std::string tok;
            std::vector<float> nums;
            while(std::getline(vs, tok, ',')) {
                try { nums.push_back(std::stof(trimStr(tok))); }
                catch(...) {}
            }
            if(nums.size() >= 1) ann.defVal = nums[0];
            if(nums.size() >= 2) ann.minVal = nums[1];
            if(nums.size() >= 3) ann.maxVal = nums[2];
        }

        if(!ann.name.empty()) result.push_back(ann);
    }
    return result;
}

// Feature 3+2: adjust the number of registered param sliders and rename them.
void scDynGenNode::updateParamCount(int newCount,
                                    const std::vector<ParamAnnotation>& anns) {
    newCount = std::max(0, std::min(newCount, kMaxParams));

    // Check if anything actually needs to change
    bool countChanged = (newCount != activeParamCount);
    bool namesChanged = false;
    if(!countChanged) {
        for(int i = 0; i < newCount; i++) {
            std::string expectedName = (i < (int)anns.size() && !anns[i].name.empty())
                                       ? anns[i].name : ("P" + std::to_string(i));
            if(paramSlots[i].param.getName() != expectedName) {
                namesChanged = true;
                break;
            }
        }
    }
    if(!countChanged && !namesChanged) return;

    // ── Step 1: Remove the editor widget so params are re-added before it ─────
    // This keeps the Oceanode panel order: [Num Channels][params...][Editor].
    removeParameter("EEL2 Editor");

    // ── Step 2: Remove all currently-registered params ────────────────────────
    for(int i = 0; i < activeParamCount; i++) {
        removeParameter(paramSlots[i].param.getName());
    }

    // ── Step 3: Update storage and re-register params ─────────────────────────
    for(int i = 0; i < newCount; i++) {
        std::string name = (i < (int)anns.size() && !anns[i].name.empty())
                           ? anns[i].name : ("P" + std::to_string(i));
        float minV = (i < (int)anns.size()) ? anns[i].minVal : 0.0f;
        float maxV = (i < (int)anns.size()) ? anns[i].maxVal : 1.0f;
        float defV = (i < (int)anns.size()) ? anns[i].defVal : 0.0f;
        if(minV >= maxV) maxV = minV + 1.0f;

        if(i < activeParamCount) {
            // Existing slot: rename + update range, preserve current value
            paramSlots[i].param.setName(name);
            paramSlots[i].param.setMin(vector<float>{minV});
            paramSlots[i].param.setMax(vector<float>{maxV});
        } else {
            // New slot: initialise with annotation default
            paramSlots[i].param.set(name,
                vector<float>{defV},
                vector<float>{minV},
                vector<float>{maxV});
        }
        addParameter(paramSlots[i].param);
    }

    // ── Step 4: Re-add the editor widget at the end ───────────────────────────
    addParameter(editorRegion,
        ofxOceanodeParameterFlags_DisableInConnection  |
        ofxOceanodeParameterFlags_DisableOutConnection |
        ofxOceanodeParameterFlags_DisableSavePreset    |
        ofxOceanodeParameterFlags_DisableSaveProject);

    activeParamCount = newCount;
    rebuildParamListeners();

    // Push any existing values to live synths
    for(auto& pair : synthInstances) {
        if(pair.second) sendParamsToSynth(pair.first);
    }
}

// Feature 1+2: rebuild param listeners (called whenever count or names change).
void scDynGenNode::rebuildParamListeners() {
    paramListeners.clear();
    for(int i = 0; i < activeParamCount; i++) {
        int idx = i;
        paramListeners.push_back(std::make_unique<ofEventListener>(
            paramSlots[idx].param.newListener([this, idx](vector<float>& v) {
                int n = numChannels.get();
                auto expanded = expandToChannels(v, n);
                std::string pname = "p" + std::to_string(idx);
                for(auto& pair : synthInstances) {
                    if(pair.second) pair.second->set(pname, expanded);
                }
            })
        ));
    }
}

// Rebuild accParamNames from annotations (used in sendCodeToServer).
void scDynGenNode::mergeParamNames(const std::vector<ParamAnnotation>& anns) {
    accParamNames.clear();
    for(auto& ann : anns) {
        std::string lc = ann.name;
        std::transform(lc.begin(), lc.end(), lc.begin(), ::tolower);
        if(std::find(accParamNames.begin(), accParamNames.end(), lc)
           == accParamNames.end()) {
            accParamNames.push_back(lc);
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Feature 4: script file management
// ─────────────────────────────────────────────────────────────────────────────

void scDynGenNode::refreshScriptList() {
    scriptFiles.clear();
    ofDirectory dir(ofToDataPath("Supercollider/dyngenScripts"));
    dir.allowExt("eel2");
    if(dir.exists()) {
        dir.listDir();
        for(int i = 0; i < (int)dir.size(); i++) {
            scriptFiles.push_back(dir.getPath(i));
        }
    }
    scriptListDirty   = false;
    selectedScriptIdx = std::min(selectedScriptIdx, (int)scriptFiles.size() - 1);
    if(selectedScriptIdx < 0) selectedScriptIdx = 0;
}

void scDynGenNode::loadScriptFile(const std::string& path) {
    std::ifstream f(path);
    if(!f.is_open()) {
        eel2StatusMsg = "Error: cannot open file";
        return;
    }
    std::string code((std::istreambuf_iterator<char>(f)),
                      std::istreambuf_iterator<char>());
    // Set param directly (bypasses debounce) so annotations/param names
    // update immediately and synths are recreated with the new @init.
    codeRequiresRecreate = true;
    eel2CodeParam.set(code);   // fires listener: parse→updateParams→send→recreate
    eel2StatusMsg   = "Loaded: " + ofFilePath::getFileName(path);
    scriptListDirty = false;
}

void scDynGenNode::saveScriptFile(const std::string& path) {
    // Ensure the directory exists
    std::string dir = ofFilePath::getEnclosingDirectory(path);
    ofDirectory::createDirectory(dir, false, true);

    std::ofstream f(path);
    if(!f.is_open()) {
        eel2StatusMsg = "Error: cannot save file";
        return;
    }
    f << std::string(editorBuf);
    eel2StatusMsg  = "Saved: " + ofFilePath::getFileName(path);
    scriptListDirty = true;  // trigger re-scan on next draw
}

// ─────────────────────────────────────────────────────────────────────────────
// Feature 6: LLM code generation
// ─────────────────────────────────────────────────────────────────────────────

std::string scDynGenNode::buildDynGenSystemPrompt() {
    return
R"SYSPROMPT(You are an EEL2 code generator for the DynGen node in Oceanode, a modular audio environment built on SuperCollider. DynGen executes EEL2 at audio rate inside a SC UGen.

Output ONLY valid EEL2 code. No markdown, no code fences, no prose before or after. Start directly with //@param declarations, @init, or @sample.

=== CRITICAL CONSTRAINTS — violating any of these produces silence, explosions, or crashes ===
1. num_ch is NEVER available (always 0). ALWAYS hardcode n (the channel count given in the request).
2. $pi is NOT defined. Use 6.28318530 for 2π and 3.14159265 for π.
3. out(variable) does NOT write to output channels. Use named output variables: out0  out1  out2 etc.
4. No file I/O, no strings, no external calls, no classes.
5. buf[] is the ONLY persistent heap. Partition it in @init with non-overlapping base offsets.
6. Keep total buf[] usage (sum of ALL buffer sizes) under 100000 floats to avoid heap aliasing.
7. Each buffer MUST wrap using ITS OWN size — never use a shared max_size for wrap-around.
8. Available functions: exp() sin() cos() tan() log() sqrt() abs() floor() ceil() max() min() pow() atan() atan2()
9. srate (float, sample rate) is available in all sections.
10. Conditional: condition ? value_if_true : value_if_false

=== PARAM DECLARATION ===
//@param Name : default, min, max
Maximum 8 params (p0..p7). Must appear at the top of the file before @init.

=== INPUT MEMORY LAYOUT ===
For n audio channels and P params, in() is a flat array:
  in(0) .. in(n-1)          = current audio input samples
  in(n + pi*n + ci)         = param pi, channel ci

Mono   (n=1):  in(1)=p0        in(2)=p1        in(3)=p2    ...
Stereo (n=2):  in(2)=p0_ch0    in(3)=p0_ch1    in(4)=p1_ch0    in(5)=p1_ch1 ...

For params that do not vary per-channel, always read channel 0: in(n + pi*n + 0)

=== OUTPUT VARIABLES ===
Write to out0 .. out(n-1). Do NOT use out(variable).
  Mono:   write out0
  Stereo: write out0 and out1

=== CODE SECTIONS ===
@init   — runs once at script load. Init buf[], write pointers, filter states, constants.
@block  — runs once per audio block (before @sample). Read params. Compute block-rate coefficients.
@sample — runs once per audio sample. Read in(). Write out0/out1/etc.

=== DELAY LINE / RING BUFFER PATTERN ===
@init
  size_A = 4096;   // smallest power-of-2 >= longest delay in samples
  ofs_A  = 0;      // unique base offset for this buffer
  w_A    = 0;      // write pointer
  // For a second buffer: ofs_B = ofs_A + size_A; etc.
@sample
  buf[ofs_A + w_A] = signal_to_store;
  r = w_A - delay_samps; r < 0 ? r += size_A;
  delayed = buf[ofs_A + r];
  w_A += 1; w_A >= size_A ? w_A = 0;

=== ONE-POLE LOW-PASS FILTER PATTERN ===
@init
  lp_state = 0;
@block
  cutoff_hz = in(n + 0*n + 0);  // p0, ch0
  lp_a = 1.0 - exp(-6.28318530 * cutoff_hz / srate);
@sample
  lp_state += lp_a * (in(0) - lp_state);
  out0 = lp_state;

=== EXAMPLES ===

// Stereo passthrough (n=2)
@sample
out0 = in(0);
out1 = in(1);

// Mono hard-clip distortion (n=1)
//@param Drive : 3.0, 1.0, 20.0
//@param Mix   : 0.5, 0.0, 1.0
@block
drive = in(1);   // p0 (n=1 → in(1+0))
mix   = in(2);   // p1 (n=1 → in(1+1))
@sample
wet = in(0) * drive;
wet = max(-1.0, min(1.0, wet));
out0 = in(0) * (1-mix) + wet * mix;

// Stereo ping-pong delay (n=2)
//@param DelayMs  : 250.0, 1.0, 2000.0
//@param Feedback : 0.5,   0.0, 0.95
//@param Mix      : 0.4,   0.0, 1.0
@init
d_size = 16384;
dL_ofs = 0;
dR_ofs = 16384;
dL_w   = 0;
dR_w   = 0;
@block
delay_ms = in(2);    // p0 ch0 (n=2 → in(2+0*2+0)=in(2))
feedback = in(4);    // p1 ch0 (n=2 → in(2+1*2+0)=in(4))
mix      = in(6);    // p2 ch0 (n=2 → in(2+2*2+0)=in(6))
d_len = max(1, min(d_size-1, floor(delay_ms * srate * 0.001)));
@sample
rL = dL_w - d_len; rL < 0 ? rL += d_size;
rR = dR_w - d_len; rR < 0 ? rR += d_size;
dL_now = buf[dL_ofs + rL];
dR_now = buf[dR_ofs + rR];
buf[dL_ofs + dL_w] = in(0) + dR_now * feedback;
buf[dR_ofs + dR_w] = in(1) + dL_now * feedback;
dL_w += 1; dL_w >= d_size ? dL_w = 0;
dR_w += 1; dR_w >= d_size ? dR_w = 0;
out0 = in(0)*(1-mix) + dL_now*mix;
out1 = in(1)*(1-mix) + dR_now*mix;

// Mono sine oscillator / test tone (n=1)
//@param Freq : 440.0, 20.0, 20000.0
//@param Amp  : 0.5,   0.0, 1.0
@init
phase = 0;
@block
freq = in(1);   // p0
amp  = in(2);   // p1
phase_inc = 6.28318530 * freq / srate;
@sample
out0 = sin(phase) * amp;
phase += phase_inc;
phase >= 6.28318530 ? phase -= 6.28318530;
)SYSPROMPT";
}

std::string scDynGenNode::callAnthropicAPI(const std::string& fullPrompt,
                                            const std::string& systemPrompt,
                                            const std::string& apiKey) {
    try {

        // Build request JSON using ofJson (nlohmann::json, always in OF)
        ofJson requestBody = {
            {"model",      "claude-sonnet-4-5"},
            {"max_tokens", 2048},
            {"system",     systemPrompt},
            {"messages",   ofJson::array({{{"role", "user"}, {"content", fullPrompt}}})}
        };
        std::string bodyStr = requestBody.dump();

        // Write body to a temp file so we don't have to shell-escape the JSON
        std::string tmpPath = std::string(std::getenv("TMPDIR") ? std::getenv("TMPDIR") : "/tmp")
                              + "/dyngen_api_req.json";
        {
            std::ofstream tf(tmpPath);
            if(!tf.is_open()) return "// Error: cannot write temp file " + tmpPath;
            tf << bodyStr;
        }

        // Use curl (always on macOS) — runs in our std::async thread, no audio impact
        std::string cmd =
            "curl -s"
            " -X POST https://api.anthropic.com/v1/messages"
            " -H 'content-type: application/json'"
            " -H 'x-api-key: " + apiKey + "'"
            " -H 'anthropic-version: 2023-06-01'"
            " -d @" + tmpPath +
            " 2>&1";

        FILE* pipe = popen(cmd.c_str(), "r");
        if(!pipe) return "// Error: popen failed";

        std::string respStr;
        char buf[4096];
        while(fgets(buf, sizeof(buf), pipe))
            respStr += buf;
        pclose(pipe);

        // Clean up temp file
        std::remove(tmpPath.c_str());

        // Parse JSON response
        ofJson obj = ofJson::parse(respStr);

        // Surface API-level errors (auth failure, rate limit, etc.)
        if(obj.contains("error"))
            return "// API error: " + obj["error"].value("message", "unknown error");

        auto& content = obj["content"];
        if(!content.is_array() || content.empty())
            return "// Error: unexpected response format";
        return content[0].value("text", "");

    } catch(const std::exception& e) {
        return std::string("// Error: ") + e.what();
    }
}

void scDynGenNode::requestLLMCode(const std::string& userPrompt) {
    if(llmApiKey.empty()) {
        llmStatusMsg = "// Error: no API key. Place key in data/anthropic_api_key.txt";
        llmHasError  = true;
        llmDone.store(true);
        return;
    }

    llmPending.store(true);
    llmDone.store(false);
    llmHasError  = false;
    llmStatusMsg = "Generating...";

    // Capture everything needed before launching the thread (no this in thread)
    int         n    = numChannels.get();
    std::string sysP = buildDynGenSystemPrompt();
    std::string key  = llmApiKey;

    std::string fullPrompt;
    if(llmFixMode) {
        std::string issue = userPrompt.empty()
            ? "Fix any bugs and make sure the script runs correctly."
            : "Issue: " + userPrompt;
        fullPrompt =
            "Fix this EEL2 script for n=" + std::to_string(n) + " channels.\n\n"
            "Current code:\n" + std::string(editorBuf) + "\n\n" + issue;
    } else {
        fullPrompt =
            "Generate an EEL2 script for n=" + std::to_string(n) + " channels.\n\n"
            + userPrompt;
    }

    llmFuture = std::async(std::launch::async,
        [fullPrompt, sysP, key]() -> std::string {
            return callAnthropicAPI(fullPrompt, sysP, key);
        });
}

// ─────────────────────────────────────────────────────────────────────────────
// ImGui editor widget (Features 4+5)
// ─────────────────────────────────────────────────────────────────────────────

void scDynGenNode::drawEditor() {
    ImDrawList* dl     = ImGui::GetWindowDrawList();
    ImVec2      cursor = ImGui::GetCursorScreenPos();

    const float W      = editorWidth.get();
    const float H      = editorHeight.get();
    const float pad    = 4.0f;
    const float rowH   = ImGui::GetTextLineHeight() + 4.0f;  // toolbar row height
    const float statusH= 16.0f;

    // Lazy-refresh script list
    if(scriptListDirty) refreshScriptList();

    // ── Overall background ────────────────────────────────────────────────────
    const float totalH = rowH + H + statusH + pad * 4;
    dl->AddRectFilled(
        cursor,
        ImVec2(cursor.x + W + pad * 2, cursor.y + totalH),
        IM_COL32(10, 12, 18, 255), 4.0f);

    // ── Toolbar row 1: file buttons + script dropdown ─────────────────────────
    ImGui::SetCursorScreenPos(ImVec2(cursor.x + pad, cursor.y + pad));

    // Open / Save
    ImGui::PushStyleColor(ImGuiCol_Button,        IM_COL32(35, 55, 85, 255));
    ImGui::PushStyleColor(ImGuiCol_ButtonHovered,  IM_COL32(50, 80, 120, 255));
    ImGui::PushStyleColor(ImGuiCol_ButtonActive,   IM_COL32(70, 110, 160, 255));

    if(ImGui::Button("Open", ImVec2(46, 0))) pendingLoadDialog = true;
    ImGui::SameLine(0, 4);
    if(ImGui::Button("Save", ImVec2(46, 0))) pendingSaveDialog = true;
    ImGui::SameLine(0, 4);

    // Feature 5: wrap-view toggle (always visible, green when active)
    {
        bool wv = wrapView;
        if(wv) ImGui::PushStyleColor(ImGuiCol_Button, IM_COL32(45, 90, 45, 255));
        if(ImGui::Button(wv ? "Edit" : "Wrap", ImVec2(46, 0))) wrapView = !wrapView;
        if(wv) ImGui::PopStyleColor();
    }
    ImGui::SameLine(0, 4);

    // Feature 6: AI generate button
    {
        bool busy = llmPending.load();
        ImGui::PushStyleColor(ImGuiCol_Button,
            busy ? IM_COL32(40, 20, 65, 255) : IM_COL32(60, 38, 90, 255));
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, IM_COL32(90, 58, 130, 255));
        ImGui::PushStyleColor(ImGuiCol_ButtonActive,  IM_COL32(115, 78, 165, 255));
        if(ImGui::Button(busy ? "···" : "AI", ImVec2(34, 0)) && !busy) {
            ImGui::OpenPopup("##llm_popup");
        }
        ImGui::PopStyleColor(3);
    }
    ImGui::SameLine(0, 4);

    // Script dropdown — list .eel2 files from dyngenScripts/
    if(!scriptFiles.empty()) {
        // Build label list (file name without path)
        std::vector<std::string> names;
        for(auto& fp : scriptFiles)
            names.push_back(ofFilePath::getFileName(fp));
        std::vector<const char*> items;
        for(auto& n : names) items.push_back(n.c_str());

        ImGui::PushStyleColor(ImGuiCol_FrameBg, IM_COL32(25, 38, 58, 255));
        // Combo width = W minus all fixed-width toolbar elements:
        //   Open(46)+gap(4)+Save(46)+gap(4)+Wrap(46)+gap(4)+AI(34)+gap(4) = 192 before
        //   gap(4)+Load(46) = 50 after  →  total non-combo = 242; -4 margin
        ImGui::SetNextItemWidth(W - 246.0f);
        ImGui::Combo("##scripts", &selectedScriptIdx, items.data(), (int)items.size());
        ImGui::PopStyleColor();
        ImGui::SameLine(0, 4);
        if(ImGui::Button("Load##file", ImVec2(46, 0))) {
            if(selectedScriptIdx >= 0 && selectedScriptIdx < (int)scriptFiles.size()) {
                loadScriptFile(scriptFiles[selectedScriptIdx]);
            }
        }
    } else {
        ImGui::PushStyleColor(ImGuiCol_Text, IM_COL32(80, 90, 100, 200));
        ImGui::TextUnformatted("(no scripts)");
        ImGui::PopStyleColor();
    }

    ImGui::PopStyleColor(3);  // Button colors (Open, Save base colors)

    // ── Text area ─────────────────────────────────────────────────────────────
    ImGui::SetCursorScreenPos(ImVec2(cursor.x + pad, cursor.y + pad + rowH + 2.0f));

    ImGui::PushStyleColor(ImGuiCol_FrameBg,       IM_COL32(18, 22, 30, 255));
    ImGui::PushStyleColor(ImGuiCol_Text,           IM_COL32(195, 220, 175, 255));
    ImGui::PushStyleColor(ImGuiCol_ScrollbarBg,    IM_COL32(10, 12, 18, 200));
    ImGui::PushStyleColor(ImGuiCol_ScrollbarGrab,  IM_COL32(60, 80, 120, 200));
    ImGui::PushStyleColor(ImGuiCol_ChildBg,        IM_COL32(18, 22, 30, 255));

    if(wrapView) {
        // ── Feature 5: word-wrap read-only view ──────────────────────────────
        // TextWrapped wraps at the current window/child width.
        ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(4, 4));
        bool childOpen = ImGui::BeginChild("##wrapview",
            ImVec2(W, H), false,
            ImGuiWindowFlags_None);
        if(childOpen) {
            // Click anywhere in the child to switch back to edit mode
            if(ImGui::IsMouseClicked(0) && ImGui::IsWindowHovered())
                wrapView = false;
            ImGui::TextWrapped("%s", editorBuf);
        }
        ImGui::EndChild();
        ImGui::PopStyleVar();

        // Hint overlay
        ImVec2 editHintPos = ImVec2(cursor.x + pad + W - 100.0f,
                                    cursor.y + pad + rowH + 6.0f);
        dl->AddText(editHintPos, IM_COL32(80, 100, 80, 180), "click to edit");
    } else {
        // ── Normal editable mode ──────────────────────────────────────────────
        bool changed = ImGui::InputTextMultiline(
            "##dyngen_eel2",
            editorBuf, kBufSize,
            ImVec2(W, H),
            ImGuiInputTextFlags_AllowTabInput);

        if(changed) {
            codeDirty      = true;
            codeDirtyTimer = 0.0f;
            eel2StatusMsg  = "Editing...";
        }
    }

    ImGui::PopStyleColor(5);

    // ── Status bar ────────────────────────────────────────────────────────────
    float statusY = cursor.y + pad + rowH + 2.0f + H + 2.0f;
    ImU32 statusCol = (eel2StatusMsg.find("Error") != std::string::npos)
                    ? IM_COL32(255, 80, 80, 255)
                    : IM_COL32(110, 200, 110, 255);
    dl->AddText(ImVec2(cursor.x + pad, statusY), statusCol, eel2StatusMsg.c_str());

    // ── Feature 6: AI generate popup ─────────────────────────────────────────
    ImGui::SetNextWindowSize(ImVec2(520, 230), ImGuiCond_Appearing);
    if(ImGui::BeginPopup("##llm_popup", ImGuiWindowFlags_None)) {

        // Header
        ImGui::TextColored(ImVec4(0.72f, 0.60f, 1.0f, 1.0f),
            "Ask Claude to write EEL2 code");
        ImGui::SameLine();
        if(llmApiKey.empty())
            ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "  [No API key]");
        else
            ImGui::TextColored(ImVec4(0.35f, 1.0f, 0.55f, 1.0f), "  [Key loaded]");

        ImGui::TextDisabled("Using n=%d channels (matches Num Channels setting on the node).",
            numChannels.get());
        ImGui::Spacing();

        // ── Mode toggle ───────────────────────────────────────────────────────
        auto modeBtn = [&](const char* label, bool active) -> bool {
            ImGui::PushStyleColor(ImGuiCol_Button,
                active ? IM_COL32(65, 40, 95, 255) : IM_COL32(28, 28, 38, 255));
            ImGui::PushStyleColor(ImGuiCol_ButtonHovered, IM_COL32(90, 58, 130, 255));
            bool clicked = ImGui::Button(label, ImVec2(122, 0));
            ImGui::PopStyleColor(2);
            return clicked;
        };
        if(modeBtn("  Generate  ##m", !llmFixMode)) llmFixMode = false;
        ImGui::SameLine(0, 2);
        if(modeBtn(" Fix current ##m", llmFixMode))  llmFixMode = true;

        ImGui::Separator();
        ImGui::Spacing();

        if(llmPending.load()) {
            // Spinner while waiting
            static const char* kSpinChars = "|/-\\";
            static int sSpin = 0;
            sSpin = (sSpin + 1) % 4;
            ImGui::Text("Generating... %c", kSpinChars[sSpin]);
            ImGui::TextDisabled("Waiting for Claude's response.");

        } else if(llmDone.load()) {
            if(llmHasError) {
                ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1,0.4f,0.4f,1));
                ImGui::TextWrapped("%s", llmStatusMsg.c_str());
                ImGui::PopStyleColor();
                ImGui::Spacing();
                if(ImGui::Button("Close##llmerr", ImVec2(80, 0))) {
                    llmDone.store(false);
                    llmHasError = false;
                    ImGui::CloseCurrentPopup();
                }
            } else {
                // Success: code was injected into editorBuf by update() — auto-close
                llmDone.store(false);
                ImGui::CloseCurrentPopup();
            }

        } else {
            // Normal prompt-input state
            ImGui::InputTextMultiline("##llm_input", llmPromptBuf,
                sizeof(llmPromptBuf), ImVec2(504, 100));
            if(llmFixMode)
                ImGui::TextDisabled("Describe the issue, or leave empty for a general fix.");
            else
                ImGui::TextDisabled("Describe the EEL2 effect, synth, or processor you want.");
            ImGui::Spacing();

            // Generate requires a non-empty prompt; Fix can run with empty prompt
            bool canGenerate = !llmApiKey.empty() && (!llmFixMode || true)
                               && (llmFixMode || llmPromptBuf[0] != '\0');
            if(!canGenerate) ImGui::BeginDisabled();
            const char* btnLabel = llmFixMode ? "Fix code##llm" : "Generate##llm";
            if(ImGui::Button(btnLabel, ImVec2(100, 0)))
                requestLLMCode(std::string(llmPromptBuf));
            if(!canGenerate) ImGui::EndDisabled();

            ImGui::SameLine(0, 10);
            if(ImGui::Button("Cancel##llm", ImVec2(70, 0)))
                ImGui::CloseCurrentPopup();

            if(llmApiKey.empty()) {
                ImGui::Spacing();
                ImGui::TextColored(ImVec4(1, 0.65f, 0.3f, 1), "No API key found. Add one of:");
                ImGui::TextDisabled("  data/anthropic_api_key.txt  (just paste the key as plain text)");
                ImGui::TextDisabled("  ~/.anthropic_api_key");
                ImGui::TextDisabled("  ANTHROPIC_API_KEY env var");
            }
        }

        ImGui::EndPopup();
    }

    // ── Advance cursor ────────────────────────────────────────────────────────
    ImGui::SetCursorScreenPos(ImVec2(cursor.x, cursor.y + totalH));
    ImGui::Dummy(ImVec2(W + pad * 2, 2.0f));
}
